#!/usr/bin/env python3
"""
Agent Zero Desktop - Python Backend Build Script

This script builds the Python backend as a standalone executable using PyInstaller.
It handles platform-specific configurations and bundles all necessary data files.

Usage:
    python build_python.py [--platform windows|macos|linux] [--one-file] [--debug]
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


def get_project_root() -> Path:
    """Get the project root directory (parent of desktop/)."""
    return Path(__file__).parent.parent.parent.resolve()


def get_desktop_dir() -> Path:
    """Get the desktop directory."""
    return Path(__file__).parent.parent.resolve()


def get_platform_name() -> str:
    """Get the current platform name."""
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    elif system == "windows":
        return "windows"
    else:
        return "linux"


def get_binary_name(plat: str) -> str:
    """Get the binary name for the platform."""
    base_name = "agent-zero-backend"
    if plat == "windows":
        return f"{base_name}.exe"
    return base_name


def get_target_triple(plat: str) -> str:
    """Get the Tauri target triple for sidecar naming."""
    arch = platform.machine().lower()
    
    if plat == "windows":
        if arch in ("amd64", "x86_64"):
            return "x86_64-pc-windows-msvc"
        elif arch in ("arm64", "aarch64"):
            return "aarch64-pc-windows-msvc"
    elif plat == "macos":
        if arch in ("x86_64", "amd64"):
            return "x86_64-apple-darwin"
        elif arch in ("arm64", "aarch64"):
            return "aarch64-apple-darwin"
    else:  # linux
        if arch in ("x86_64", "amd64"):
            return "x86_64-unknown-linux-gnu"
        elif arch in ("arm64", "aarch64"):
            return "aarch64-unknown-linux-gnu"
    
    raise ValueError(f"Unsupported platform/arch combination: {plat}/{arch}")


def ensure_dependencies():
    """Ensure PyInstaller is installed."""
    try:
        import PyInstaller
        print(f"PyInstaller version: {PyInstaller.__version__}")
    except ImportError:
        print("Installing PyInstaller...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller>=6.0.0"])


def build_pyinstaller(
    project_root: Path,
    output_dir: Path,
    plat: str,
    one_file: bool = False,
    debug: bool = False,
):
    """Build the Python backend with PyInstaller."""
    
    # Data files to include
    data_files = [
        ("webui", "webui"),
        ("prompts", "prompts"),
        ("knowledge", "knowledge"),
        ("agents", "agents"),
        ("plugins", "plugins"),
        ("conf", "conf"),
        ("extensions", "extensions"),
        ("lib", "lib"),
    ]
    
    # Build the spec file content
    datas_spec = ",\n        ".join([
        f"(r'{project_root / src}', r'{dst}')"
        for src, dst in data_files
        if (project_root / src).exists()
    ])
    
    # Hidden imports that PyInstaller might miss
    hidden_imports = [
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "flask",
        "flask.json",
        "werkzeug",
        "socketio",
        "engineio",
        "starlette",
        "starlette.routing",
        "starlette.middleware",
        "wsproto",
        "nest_asyncio",
        "tiktoken",
        "tiktoken_ext",
        "tiktoken_ext.openai_public",
        "sentence_transformers",
        "langchain",
        "langchain_core",
        "langchain_community",
        "faiss",
        "numpy",
        "PIL",
    ]
    
    hidden_imports_spec = ",\n        ".join([f"'{imp}'" for imp in hidden_imports])
    
    # Exclude modules to reduce size
    excludes = [
        "matplotlib",
        "tkinter",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "IPython",
        "jupyter",
        "notebook",
    ]
    
    excludes_spec = ",\n        ".join([f"'{exc}'" for exc in excludes])
    
    # Create spec file
    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
# Agent Zero Desktop - PyInstaller Spec File
# Auto-generated by build_python.py

import sys
import os

block_cipher = None

# Project paths
PROJECT_ROOT = r'{project_root}'
sys.path.insert(0, PROJECT_ROOT)

a = Analysis(
    [r'{project_root / "run_ui.py"}'],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=[
        {datas_spec}
    ],
    hiddenimports=[
        {hidden_imports_spec}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        {excludes_spec}
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

'''
    
    binary_name = get_binary_name(plat).replace('.exe', '')
    
    if one_file:
        spec_content += f'''
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{binary_name}',
    debug={debug},
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''
    else:
        spec_content += f'''
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{binary_name}',
    debug={debug},
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{binary_name}',
)
'''
    
    # Write spec file
    spec_path = output_dir / "agent-zero.spec"
    output_dir.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(spec_content)
    print(f"Created spec file: {spec_path}")
    
    # Run PyInstaller
    pyinstaller_args = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath", str(output_dir / "dist"),
        "--workpath", str(output_dir / "build"),
        str(spec_path),
    ]
    
    print(f"Running PyInstaller: {' '.join(pyinstaller_args)}")
    subprocess.check_call(pyinstaller_args, cwd=project_root)
    
    # Copy to Tauri binaries location
    target_triple = get_target_triple(plat)
    tauri_binaries_dir = get_desktop_dir() / "src-tauri" / "binaries"
    tauri_binaries_dir.mkdir(parents=True, exist_ok=True)
    
    if one_file:
        src_binary = output_dir / "dist" / get_binary_name(plat)
        dst_binary = tauri_binaries_dir / f"agent-zero-backend-{target_triple}{'.exe' if plat == 'windows' else ''}"
        shutil.copy2(src_binary, dst_binary)
        print(f"Copied binary to: {dst_binary}")
    else:
        src_dir = output_dir / "dist" / binary_name
        dst_dir = tauri_binaries_dir / f"agent-zero-backend-{target_triple}"
        if dst_dir.exists():
            shutil.rmtree(dst_dir)
        shutil.copytree(src_dir, dst_dir)
        print(f"Copied directory to: {dst_dir}")
    
    print("Python backend build complete!")


def main():
    parser = argparse.ArgumentParser(description="Build Agent Zero Python backend")
    parser.add_argument(
        "--platform",
        choices=["windows", "macos", "linux"],
        default=get_platform_name(),
        help="Target platform (default: auto-detect)",
    )
    parser.add_argument(
        "--one-file",
        action="store_true",
        help="Create a single executable file (slower startup)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Build with debug information",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory (default: desktop/python-dist)",
    )
    
    args = parser.parse_args()
    
    project_root = get_project_root()
    output_dir = args.output or (get_desktop_dir() / "python-dist")
    
    print(f"Project root: {project_root}")
    print(f"Output directory: {output_dir}")
    print(f"Platform: {args.platform}")
    print(f"One-file mode: {args.one_file}")
    print(f"Debug mode: {args.debug}")
    
    ensure_dependencies()
    build_pyinstaller(
        project_root=project_root,
        output_dir=output_dir,
        plat=args.platform,
        one_file=args.one_file,
        debug=args.debug,
    )


if __name__ == "__main__":
    main()
